name: deploy-project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm packages  
        run: npm install

      - name: Run tests  
        run: npm run test:unit

      - name: Build the project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         role-duration-seconds: 1200
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         role-to-assume: ${{ secrets.AWS_S3_ROLE_TO_ASSUME }}
         aws-region: eu-central-1

      - name: Copy files with the AWS CLI
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}

