name: deploy-project

on:
  push:
    branches:
      - main
    paths: 
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test:unit
      - run: npm run build

      - uses: unfor19/install-aws-cli-action@v1.0.3
      - run: aws S3 sync dist S3://${{ secrets.AWS_S3_BUCKET_NAME }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}